//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Densha.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Densha.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   _TAG_ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DndIdTag {
            get {
                return ResourceManager.GetString("DndIdTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロジェクトが変更されています。
        ///保存しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_ConfirmSaveProject {
            get {
                return ResourceManager.GetString("Message_ConfirmSaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Densha Project File(*.xml)|*.xml|すべてのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProjectFileFilter {
            get {
                return ResourceManager.GetString("ProjectFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   電写 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_MyName {
            get {
                return ResourceManager.GetString("Title_MyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_NewProject {
            get {
                return ResourceManager.GetString("Title_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロジェクトを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_OpenProjectFile {
            get {
                return ResourceManager.GetString("Title_OpenProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_ProjectChangedMark {
            get {
                return ResourceManager.GetString("Title_ProjectChangedMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロジェクトを保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_SaveProjectFile {
            get {
                return ResourceManager.GetString("Title_SaveProjectFile", resourceCulture);
            }
        }
    }
}
